apiVersion: v1alpha
kind: apitest
sauce:
  region: us-west-1
  metadata:
    build: "risingland build"
  # tunnel:
  #   name: tunnelname
  #   owner: tunnelowner

rootDir: .

suites:
  # Remote Suite #1 will run in parallel all tests:
  # - Published in project "saucectl-apitest-sauce_tests"
  # - Having the "contract" tag
  - name: "Remote Suite #1"
    projectName: risingland
    useRemoteTests: true
    tags:
      - basic

  # Dynamic Suite #1 will run all tests found in rootDir ("."), and matching any of the "testMatch" values.
  # Those tests will be attached to the project "saucectl-apitest-sauce_tests".
  - name: "Dynamic Suite #1"
    projectName: risingland
    testMatch:
      - 01 Send Notification
      - 02 Upload Image
      - 03 Add Feedback
      - 04 Get Feedback
      - 05 Get Commands
      - 06 Rising Chat
      - 07 Train Contacts
      - 08 Image Relatedness